global:
  imageRegistry: YOUR_ECR_URL
  imageTag: latest
  namespace: ecommerce
  env: production

services:
  user-service:    {enabled: true}
  product-service: {enabled: true}
  order-service:   {enabled: true}
  payment-service: {enabled: true}
  notification-service: {enabled: true}
  api-gateway:     {enabled: true}

externalSecrets:
  enabled: true
  secretStore: aws-secrets-manager
  refreshInterval: 1h
