apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-order
  namespace: ecommerce
spec:
  serviceName: postgres-order
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports: [{containerPort: 5432}]
          env:
            - name: POSTGRES_DB
              value: orders_db
            - name: POSTGRES_USER
              value: order_svc
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-order-secret
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests: {cpu: 100m, memory: 256Mi}
            limits:   {cpu: 500m, memory: 512Mi}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: gp3
        resources:
          requests: {storage: 20Gi}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: ecommerce
spec:
  selector:
    app: postgres-order
  clusterIP: None
  ports:
    - port: 5432
